version: '3'
services:
  redis:
    image: redis:latest
    container_name: majaliss-landing-page-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./config:/usr/local/etc/redis
    environment:
      - REDIS_USER=${REDIS_USER_NAME}
      - REDIS_PASSWORD=${REDIS_USER_PASSWORD}
